---
- name: Debug Hello World
  debug:
    msg: "Hello World from kemopq/hello_world collection!"

- name: Create a file called '/tmp/testfile.txt' with the content 'hello world'.
  copy:
    content: "Hello World from kemopq/hello_world collection"
    dest: /tmp/testfile.txt
    mode: 0666
    force: 'no'

- name: "Add sign to file /tmp/testfile.txt"
  kemopq.hello_world.signfile:
    name: Bruce willis
    path: "/tmp/testfile.txt"
  register: signfile_result

- name: DEBUG print signfile result
  debug:
    msg: "Changed={{ signfile_result.changed }} Stat={{ signfile_result.stat }} Path={{ signfile_result.path }}"
